export default [
  {
    name: "BIRMINGHAM",
    colour: "PURPLE",
    x: 33,
    y: 36,
    slots: [
      ["COTTON", "MANUFACTURER"],
      ["MANUFACTURER"],
      ["IRON"],
      ["MANUFACTURER"],
    ],
  },
  {
    name: "COVENTRY",
    colour: "PURPLE",
    x: 43,
    y: 39,
    slots: [["POTTERY"], ["MANUFACTURER", "COAL"], ["IRON", "MANUFACTURER"]],
  },
  {
    name: "NUNEATON",
    colour: "PURPLE",
    x: 42,
    y: 31,
    slots: [
      ["MANUFACTURER", "BREWERY"],
      ["COTTON", "COAL"],
    ],
  },
  {
    name: "REDDITCH",
    colour: "PURPLE",
    x: 30,
    y: 44,
    slots: [["MANUFACTURER", "COAL"], ["IRON"]],
  },
  {
    name: "COALBROOKDALE",
    colour: "YELLOW",
    x: 11,
    y: 28,
    slots: [["IRON", "BREWERY"], ["IRON"], ["COAL"]],
  },
  {
    name: "WOLVERHAMPTON",
    colour: "YELLOW",
    x: 18,
    y: 28,
    slots: [["MANUFACTURER"], ["MANUFACTURER", "COAL"]],
  },
  {
    name: "DUDLEY",
    colour: "YELLOW",
    x: 21,
    y: 34,
    slots: [["COAL"], ["IRON"]],
  },
  {
    name: "KIDDERMINSTER",
    colour: "YELLOW",
    x: 16,
    y: 41,
    slots: [["COTTON", "COAL"], ["COTTON"]],
  },
  {
    name: "WORCESTER",
    colour: "YELLOW",
    x: 18,
    y: 47,
    slots: [["COTTON"], ["COTTON"]],
  },
  {
    name: "STAFFORD",
    colour: "RED",
    x: 20,
    y: 18,
    slots: [["MANUFACTURER", "BREWERY"], ["POTTERY"]],
  },
  {
    name: "BURTON-ON-TRENT",
    colour: "RED",
    x: 36,
    y: 18,
    slots: [["MANUFACTURER", "COAL"], ["BREWERY"]],
  },
  {
    name: "CANNOCK",
    colour: "RED",
    x: 25,
    y: 22,
    slots: [["MANUFACTURER", "COAL"], ["COAL"]],
  },
  {
    name: "TAMWORTH",
    colour: "RED",
    x: 37,
    y: 25,
    slots: [
      ["COTTON", "COAL"],
      ["COTTON", "COAL"],
    ],
  },
  {
    name: "WALSALL",
    colour: "RED",
    x: 28,
    y: 29,
    slots: [
      ["IRON", "MANUFACTURER"],
      ["MANUFACTURER", "BREWERY"],
    ],
  },
  {
    name: "STOKE-ON-TRENT",
    colour: "BLUE",
    x: 21,
    y: 4,
    slots: [["COTTON", "MANUFACTURER"], ["POTTERY", "IRON"], ["MANUFACTURER"]],
  },
  {
    name: "LEEK",
    colour: "BLUE",
    x: 29,
    y: 1,
    slots: [
      ["COTTON", "MANUFACTURER"],
      ["COTTON", "COAL"],
    ],
  },
  {
    name: "STONE",
    colour: "BLUE",
    x: 15,
    y: 12,
    slots: [
      ["COTTON", "BREWERY"],
      ["MANUFACTURER", "COAL"],
    ],
  },
  {
    name: "UTTOXETER",
    colour: "BLUE",
    x: 29,
    y: 11,
    slots: [
      ["MANUFACTURER", "BREWERY"],
      ["COTTON", "BREWERY"],
    ],
  },
  {
    name: "BELPER",
    colour: "GREEN",
    x: 39,
    y: 3,
    slots: [["COTTON", "MANUFACTURER"], ["COAL"], ["POTTERY"]],
  },
  {
    name: "DERBY",
    colour: "GREEN",
    x: 40,
    y: 12,
    slots: [["COTTON", "BREWERY"], ["COTTON", "MANUFACTURER"], ["IRON"]],
  },
];
